#Requires -Version 5.1
<#
.SYNOPSIS
    project-init - generate per-project .github/copilot-instructions.md from AI-Brain sources.
.USAGE
    project-init                                # Target current directory
    project-init -ProjectPath C:\path\to\repo
    project-init -AllActiveProjects
    project-init -AllActiveProjects -DryRun
#>

param(
    [string]$ProjectPath = "",
    [switch]$AllActiveProjects,
    [switch]$DryRun,
    [switch]$Quiet,
    [string]$BrainRoot = "C:\Users\Maithil\AI-Brain",
    [string]$ActiveProjectsPath = ""
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $BrainRoot)) {
    throw "Brain root not found: $BrainRoot"
}

if (-not $ActiveProjectsPath) {
    $ActiveProjectsPath = Join-Path $BrainRoot "memory\active-projects.json"
}

function Write-Info {
    param([string]$Message)
    if (-not $Quiet) {
        Write-Host $Message
    }
}

function Normalize-Path {
    param([string]$InputPath)
    if (-not $InputPath) { return "" }
    try {
        return [System.IO.Path]::GetFullPath($InputPath).TrimEnd('\\').ToLowerInvariant()
    } catch {
        return $InputPath.TrimEnd('\\').ToLowerInvariant()
    }
}

function Get-BrainSources {
    param([string]$Root)

    $sources = @()

    $identityFiles = @(
        "identity\core-rules.md",
        "identity\preferences.md",
        "identity\profile.md",
        "identity\style.md"
    )

    $memoryFiles = @(
        "memory\active-context.md",
        "memory\decisions.md",
        "memory\learnings.md"
    )

    $skillIndex = @("skills\_index.md")

    $topLevelSkills = @()
    $skillsDir = Join-Path $Root "skills"
    if (Test-Path $skillsDir) {
        $topLevelSkills = @(Get-ChildItem -Path $skillsDir -File -Filter "*.md" -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -ne "_index.md" } |
            Sort-Object Name |
            ForEach-Object { "skills\$($_.Name)" })
    }

    $nestedSkills = @()
    if (Test-Path $skillsDir) {
        $nestedSkills = @(Get-ChildItem -Path $skillsDir -Recurse -File -Filter "SKILL.md" -ErrorAction SilentlyContinue |
            Where-Object { $_.FullName -notmatch "\\skills\\review\\" } |
            Sort-Object FullName |
            ForEach-Object {
                $_.FullName.Substring($Root.Length).TrimStart('\\')
            })
    }

    foreach ($relative in @($identityFiles + $memoryFiles + $skillIndex + $topLevelSkills + $nestedSkills)) {
        $absolute = Join-Path $Root $relative
        if (Test-Path $absolute) {
            $sources += [PSCustomObject]@{
                RelativePath = $relative
                AbsolutePath = $absolute
            }
        }
    }

    return $sources
}

function Get-ProjectSnapshot {
    param(
        [string]$ProjectsJsonPath,
        [string]$TargetProjectPath
    )

    if (-not (Test-Path $ProjectsJsonPath)) {
        return $null
    }

    try {
        $data = Get-Content -Path $ProjectsJsonPath -Raw -Encoding UTF8 | ConvertFrom-Json
    } catch {
        return $null
    }

    $targetNorm = Normalize-Path -InputPath $TargetProjectPath
    foreach ($p in $data.projects) {
        if ((Normalize-Path -InputPath $p.path) -eq $targetNorm) {
            return $p
        }
    }

    return $null
}

function Build-InstructionsContent {
    param(
        [string]$Root,
        [string]$TargetProjectPath,
        [object]$ProjectSnapshot,
        [object[]]$Sources
    )

    $lines = @()
    $lines += "# Copilot Instructions"
    $lines += ""
    $lines += "> Generated by project-init on $((Get-Date).ToString('yyyy-MM-dd HH:mm:ss'))"
    $lines += "> Brain root: $Root"
    $lines += "> Project path: $TargetProjectPath"
    $lines += "> Sources included: $($Sources.Count)"
    $lines += ""

    if ($ProjectSnapshot) {
        $tech = if ($ProjectSnapshot.techStack -and $ProjectSnapshot.techStack.Count -gt 0) { $ProjectSnapshot.techStack -join ', ' } else { "unknown" }
        $lastMessage = if ($ProjectSnapshot.lastCommit -and $ProjectSnapshot.lastCommit.message) { $ProjectSnapshot.lastCommit.message } else { "" }

        $lines += "## Project Snapshot"
        $lines += ""
        $lines += "- Name: $($ProjectSnapshot.name)"
        $lines += "- Branch: $($ProjectSnapshot.branch)"
        $lines += "- Tech stack: $tech"
        if ($lastMessage) {
            $lines += "- Last commit: $lastMessage"
        }
        $lines += ""
    }

    foreach ($src in $Sources) {
        $lines += "## Source: $($src.RelativePath.Replace('\\', '/'))"
        $lines += ""
        $content = Get-Content -Path $src.AbsolutePath -Raw -Encoding UTF8
        if ($content) {
            $lines += $content.TrimEnd()
        }
        $lines += ""
    }

    return ($lines -join "`n")
}

function Write-ProjectInstructions {
    param(
        [string]$TargetPath,
        [string]$Root,
        [string]$ProjectsJsonPath,
        [switch]$IsDryRun
    )

    if (-not (Test-Path $TargetPath)) {
        return [PSCustomObject]@{ Project = $TargetPath; Status = "missing"; OutputPath = ""; SourceCount = 0 }
    }

    $sources = @(Get-BrainSources -Root $Root)
    $snapshot = Get-ProjectSnapshot -ProjectsJsonPath $ProjectsJsonPath -TargetProjectPath $TargetPath

    $githubDir = Join-Path $TargetPath ".github"
    $outputPath = Join-Path $githubDir "copilot-instructions.md"

    if ($IsDryRun) {
        return [PSCustomObject]@{ Project = $TargetPath; Status = "dry-run"; OutputPath = $outputPath; SourceCount = $sources.Count }
    }

    if (-not (Test-Path $githubDir)) {
        New-Item -ItemType Directory -Path $githubDir -Force | Out-Null
    }

    $payload = Build-InstructionsContent -Root $Root -TargetProjectPath $TargetPath -ProjectSnapshot $snapshot -Sources $sources
    Set-Content -Path $outputPath -Value $payload -Encoding UTF8

    return [PSCustomObject]@{ Project = $TargetPath; Status = "written"; OutputPath = $outputPath; SourceCount = $sources.Count }
}

$targets = @()
if ($AllActiveProjects) {
    if (-not (Test-Path $ActiveProjectsPath)) {
        throw "active-projects.json not found: $ActiveProjectsPath"
    }

    $data = Get-Content -Path $ActiveProjectsPath -Raw -Encoding UTF8 | ConvertFrom-Json
    $targets = @($data.projects | Where-Object { $_.isActive -eq $true } | ForEach-Object { [string]$_.path })
} elseif ($ProjectPath) {
    $targets = @($ProjectPath)
} else {
    $targets = @((Get-Location).Path)
}

$targets = @($targets | Where-Object { $_ } | Select-Object -Unique)

if ($targets.Count -eq 0) {
    Write-Info "No target projects found."
    exit 0
}

$results = @()
foreach ($target in $targets) {
    try {
        $result = Write-ProjectInstructions -TargetPath $target -Root $BrainRoot -ProjectsJsonPath $ActiveProjectsPath -IsDryRun:$DryRun
        $results += $result
    } catch {
        $results += [PSCustomObject]@{ Project = $target; Status = "error"; OutputPath = ""; SourceCount = 0; Error = $_.Exception.Message }
    }
}

foreach ($r in $results) {
    if ($r.Status -eq "written") {
        Write-Info "[OK] $($r.Project) -> $($r.OutputPath) ($($r.SourceCount) sources)"
    } elseif ($r.Status -eq "dry-run") {
        Write-Info "[DRY] $($r.Project) -> $($r.OutputPath) ($($r.SourceCount) sources)"
    } elseif ($r.Status -eq "missing") {
        Write-Info "[SKIP] $($r.Project) (path missing)"
    } else {
        Write-Info "[ERR] $($r.Project) - $($r.Error)"
    }
}

$writtenCount = @($results | Where-Object { $_.Status -eq "written" }).Count
$dryCount = @($results | Where-Object { $_.Status -eq "dry-run" }).Count
$errorCount = @($results | Where-Object { $_.Status -eq "error" }).Count

if (-not $Quiet) {
    Write-Host ""
    Write-Host "project-init summary: written=$writtenCount dry-run=$dryCount errors=$errorCount"
}
